### ISSUE TITLE
Create Exception module for error value

### ISSUE THREAD

**Issue by SimonLab** [dwyl/gitea#25]
Go over the functions' return values and make sure they are consistent by returning either `{:ok, value}` or `{:error, exception}`
This will make it easier for applications using the library to pattern match on these functions.

For the `exception` we can create our own exception module, see https://elixir-lang.org/getting-started/try-catch-and-rescue.html#errors 

see also https://medium.com/@moxicon/elixir-best-practices-for-error-values-50dc015a06f5

**Comment by nelsonic** [comment]
@SimonLab I merged your PR #26 
I get the following failed tests on **`main`** when attempting to run the tests with `mock: true`:

```sh
  1) test commit/2 creates a commit in the repo (GiteaTest)
     test/gitea_test.exs:169
     ** (MatchError) no match of right hand side value: {:error, %Git.Error{args: ["."], code: 1, command: "add", message: "The following paths are ignored by one of your .gitignore files:\ntmp\nhint: Use -f if you really want to add them.\nhint: Turn this message off by running\nhint: \"git config advice.addIgnoredFile false\"\n"}}
     code: Gitea.commit(org_name, repo_name, %{
     stacktrace:
       (gitea 1.0.5) lib/gitea.ex:227: Gitea.commit/3
       test/gitea_test.exs:182: (test)

  2) test Gitea.push/2 pushes the commit to the remote repo (GiteaTest)
     test/gitea_test.exs:195
     ** (MatchError) no match of right hand side value: {:error, %Git.Error{args: ["."], code: 1, command: "add", message: "The following paths are ignored by one of your .gitignore files:\ntmp\nhint: Use -f if you really want to add them.\nhint: Turn this message off by running\nhint: \"git config advice.addIgnoredFile false\"\n"}}
     code: Gitea.commit(org_name, repo_name, %{
     stacktrace:
       (gitea 1.0.5) lib/gitea.ex:227: Gitea.commit/3
       test/gitea_test.exs:209: (test)
```

I did a fresh `git clone` of the repo ... 🆕 
Could you please confirm that the tests pass on your `localhost`? 🙏 
They _appear_ to be fine on GitHub CI ... 💭

**Comment by nelsonic** [comment]
Meanwhile package published to https://hex.pm/packages/gitea/1.0.5 📦 🚀  (to not delay your work)

**Comment by SimonLab** [comment]
Tested again on a fresh clone, I have the same errors.
However I don't think it's link to might latest PR as I've tested on the v1.0.3 and have similar errors.
I think it might be linked to the .gitignore having tmp folder ignore:
https://github.com/dwyl/gitea/blob/5dfdb2c8134834ef0b177e2a4fb93940a33a7fa7/.gitignore#L25-L28

but 
```
# Optionally set the path where you want to clone git repos:
export GIT_TEMP_DIR_PATH=tmp
```
is using `tmp`

**Comment by nelsonic** [comment]
@SimonLab any ideas what we can do to overcome this? 
We didn't have this issue on [`gogs`](https://github.com/dwyl/gogs) because of the submodule.

**Comment by nelsonic** [comment]
Dedicated issue for creating submodule: #29
